parameters:
    env(MUSEMENT_API_BASE_URL): ''
    env(WEATHER_API_BASE_URL): ''
    env(WEATHER_API_AUTH_KEY): ''
    eight_points_guzzle.symfony_log_formatter.pattern: XXXXX {method} {uri} {code}
    eight_points_guzzle.http_client.class: App\DependencyInjection\GuzzleClientDecorated
eight_points_guzzle:
    logging: true
    slow_response_time: 1000
    clients:
        musement_api:
            class: App\ApiClient\MusementApiClient
            base_url: '%env(string:MUSEMENT_API_BASE_URL)%'
            options:
                timeout: 30
                http_errors: false
                headers:
                    Accept: 'application/json'
        weather_api:
            class: App\ApiClient\WeatherApiClient
            base_url: '%env(string:WEATHER_API_BASE_URL)%'
            options:
                timeout: 30
                http_errors: false
                query:
                    key: '%env(string:WEATHER_API_AUTH_KEY)%'
                headers:
                    Accept: 'application/json'