nelmio_api_doc:
    documentation:
        info:
            title: Musement Weather API
            description: Allows to get weather forecast per city
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api
