version: '2'

services:
  php:
    build: ./docker/php-fpm
    volumes:
      - .:/data/app/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - mysql
      - redis
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - .:/data/app/
      - ./docker/nginx/weather-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    env_file:
      - .env
  mysql:
    image: mysql:5.6
    command:
      --sql_mode=""
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]
    ports:
      - '6379'
    volumes:
      - ../data/redis:/data

volumes:
  mysql: