version: '2'

services:
  php:
    build: ./docker/php-fpm
    volumes:
      - .:/data/app/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
      - redis
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - .:/data/app/
      - ./docker/nginx/weather-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    env_file:
      - .env.local
  db:
    image: postgres:9.6.1
    restart: always
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/db
  redis:
    image: redis
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data
volumes:
  db: